### ISSUE TITLE
Screen Dimensions for Nexus 9, Android 6 - API Level 23 Emulator

### ISSUE THREAD

**Issue by alaskanrogue** [jasonCodesAway/XamJam#1]
When using the plugin against this emulator in debug mode on Visual Studio 2015, the screen dimensions are reversed, e.g. height is being reported as width.

**Comment by alaskanrogue** [comment]
Testing against the Nexus 6, Android 6 - API Level 23, emulator resulted in the same scenario. It appears that returned results from the API call is not in the order expected.

**Comment by jasonCodesAway** [comment]
Wow interesting. Thanks for the report. I'm traveling the next 2 days but can investigate this weekend. I know at one point we did test against Android and it was working, but we primarily run on UWP (just because it's faster so far).

**Comment by jasonCodesAway** [comment]
Fixed and pushed in the [latest nuget (version 1.0.5)](https://www.nuget.org/packages/Xam.Plugins.XamJam.Screen/). Thanks for the report! We were actually using screen area (width \* height) only so we missed this.
