### ISSUE TITLE
XamJam.Screen.Plugin.XamJam.Screen.UWP - Another way?

### ISSUE THREAD

**Issue by mattregul** [jasonCodesAway/XamJam#3]
Take a peak at my approach, perhaps this could be used in your UWP solution?

https://github.com/mattregul/Xamarin_Screensize/blob/master/screensize/screensize/screensize/screensize.UWP/App.xaml.cs#L60-L85
                               
```
// You decided which is best for you...
//  Do you want Size of the App's View
//      or
//  Do you want the Display's resolution 
// ######################################

// Size of App's view
DisplayScreenHeight = Windows.UI.ViewManagement.ApplicationView.GetForCurrentView().VisibleBounds.Height;
DisplayScreenWidth = Windows.UI.ViewManagement.ApplicationView.GetForCurrentView().VisibleBounds.Width;

// Size of screen's resolution
//DisplayScreenWidth = Windows.Graphics.Display.DisplayInformation.GetForCurrentView().ScreenHeightInRawPixels;
//DisplayScreenHeight = Windows.Graphics.Display.DisplayInformation.GetForCurrentView().ScreenWidthInRawPixels;

// Pixels per View Pixel
// - https://msdn.microsoft.com/en-us/windows/uwp/layout/design-and-ui-intro#effective-pixels-and-scaling
// - https://msdn.microsoft.com/en-us/windows/uwp/layout/screen-sizes-and-breakpoints-for-responsive-design
DisplayScaleFactor = Windows.Graphics.Display.DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;
```

**Comment by jasonCodesAway** [comment]
Thanks for the code! That looks promising. I just got back from vacation so I'll dive into this soon (hopefully tomorrow). Cheers from Florida

**Comment by jasonCodesAway** [comment]
Screen was meant to give the user the maximum screen size possible for the app (and my apps are full screen and don't resize, so app size = screen size - I use this info for view caching purposes). But I could extend Screen to be more generic. I'm also not a UWP guru, so I might need some education here. First question: the current method uses [Windows.UI.Xaml.Window.Current.Bounds](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.window.bounds). For the size of the app view case you're proposing using [ApplicationView](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.viewmanagement.applicationview.visiblebounds), Why is that better?

Also, can you tell me more about your use case? Do you need to handle dynamic screen sizes? Or is the size static, but you just want to be able to choose whether you're getting the app's view size vs. the total screen size?

**Comment by jasonCodesAway** [comment]
Closing as inactive/non-responsive
