### ISSUE TITLE
XamJam.Screen Does not change with orientation

### ISSUE THREAD

**Issue by OpticNectar** [jasonCodesAway/XamJam#5]
I am using this plugin on iOS and when you rotate your device the width/height are no longer correct.

**Comment by jasonCodesAway** [comment]
Thanks for the report! Sorry for the lag, work has consumed all my free time. But alas the weekend is here. I gather that the IOS UIScreen.MainScreen.Bounds.Width & Height calls don't account for rotation. I'll investigate this and the fix. Should be simple.

**Comment by jasonCodesAway** [comment]
Surprisingly I don't see an easy fix for this, and [Apple's documentation](https://developer.apple.com/documentation/uikit/uiscreen) states that the code should work as-is in iOS 8+. If you'd like this to work prior to iOS8 please submit a pull request.
